import React from 'react';
import { useParams } from 'react-router-dom';
import { mockInsights, mockThemes } from '../data/mockData';

const ProjectInsights: React.FC = () => {
  const { projectId } = useParams();

  return (
    <div className="view-container animate-fade-in">
      <div className="header-section">
        <h1 className="view-title">Automated Insights</h1>
        <p className="view-subtitle">Multimodal Synthesis for Project #{projectId}</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Insights Timeline */}
        <div className="lg:col-span-2 space-y-6">
          <div className="card glass">
            <h3 className="font-bold mb-6 text-slate-800 flex items-center gap-2">
              <span className="p-2 bg-indigo-100 rounded-lg">✨</span>
              Key "Aha!" Moments
            </h3>
            <div className="space-y-4">
              {mockInsights.map((insight) => (
                <div key={insight.id} className="p-4 rounded-xl border border-slate-100 bg-white/50 hover:bg-white transition-all">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="font-bold text-slate-900">{insight.title}</h4>
                    <span className={`badge ${insight.type === 'Critical' ? 'badge-warning' : 'badge-success'}`}>
                      {insight.type}
                    </span>
                  </div>
                  <p className="text-sm text-slate-600 mb-3">{insight.description}</p>
                  <div className="flex items-center justify-between text-xs text-slate-400">
                    <span>Generated by Gemini 1.5 Pro</span>
                    <span>{insight.timestamp}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="card glass">
            <h3 className="font-bold mb-6 text-slate-800">Video-to-Insight Synthesis</h3>
            <div className="aspect-video rounded-xl bg-slate-900 flex items-center justify-center relative overflow-hidden group">
              <div className="text-center z-10">
                <div className="w-16 h-16 rounded-full bg-indigo-500 flex items-center justify-center mx-auto mb-4 cursor-pointer group-hover:scale-110 transition-transform">
                  <div className="w-0 h-0 border-t-[10px] border-t-transparent border-l-[18px] border-l-white border-b-[10px] border-b-transparent ml-1"></div>
                </div>
                <p className="text-white font-medium">Play Insight Highlight Reel</p>
                <p className="text-slate-400 text-xs">AI-curated from 12 hours of footage</p>
              </div>
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent"></div>
            </div>
          </div>
        </div>

        {/* Sidebar Analytics */}
        <div className="space-y-6">
          <div className="card glass">
            <h3 className="font-bold mb-4 text-slate-800">Thematic Analysis</h3>
            <div className="space-y-3">
              {mockThemes.map((theme) => (
                <div key={theme.name} className="space-y-1">
                  <div className="flex justify-between text-xs font-bold uppercase tracking-tighter">
                    <span>{theme.name}</span>
                    <span className="text-slate-400">{theme.count} mentions</span>
                  </div>
                  <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className={`h-full rounded-full ${theme.sentiment === 'Positive' ? 'bg-emerald-400' : theme.sentiment === 'Negative' ? 'bg-rose-400' : 'bg-slate-400'}`}
                      style={{ width: `${(theme.count / 15) * 100}%` }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>
            <button className="btn btn-outline w-full mt-6 text-xs py-2">View Affinity Map</button>
          </div>

          <div className="card glass bg-indigo-600 text-white">
            <h3 className="font-bold mb-2">Multimodal Focus</h3>
            <p className="text-sm opacity-90 mb-4">Correlation found between verbal frustration and mouse-click clusters in the "Checkout" view.</p>
            <div className="p-4 rounded-lg bg-white/10 text-xs italic">
              "System: High confidence (92%) that address validation is the primary barrier."
            </div>
          </div>

          <div className="card glass overflow-hidden">
            <h3 className="font-bold mb-4 text-slate-800">Engagement Heatmap</h3>
            <div className="aspect-square rounded-lg bg-slate-50 heatmap-box border border-slate-100 flex items-center justify-center p-4">
              <div className="text-center">
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Click Density Layer</p>
                <div className="w-full h-px bg-slate-200 my-2"></div>
                <p className="text-[10px] text-slate-400">Gemini 3.1 Synthesis</p>
              </div>
            </div>
          </div>

          <div className="card glass">
            <h3 className="font-bold mb-4 text-slate-800">Card Sort Dendrogram</h3>
            <div className="h-40 relative flex items-center">
              <svg className="w-full h-full">
                <path d="M 0 20 L 50 20 L 50 60 L 100 60" className="dendrogram-line" />
                <path d="M 50 20 L 50 0 L 100 0" className="dendrogram-line" />
                <path d="M 0 100 L 40 100 L 40 80 L 100 80" className="dendrogram-line" />
                <path d="M 40 100 L 40 120 L 100 120" className="dendrogram-line" />
              </svg>
              <div className="absolute inset-0 flex flex-col justify-between py-2 text-[10px] text-slate-400 pl-24">
                <span>Category A</span>
                <span>Category B</span>
                <span>Category C</span>
                <span>Category D</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProjectInsights;
